# Generated by Django 3.2.5 on 2021-09-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
