# Generated by Django 3.2.5 on 2021-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210910_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=400, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
